version: "2.4"

services:
  php-gallery-manager:
    container_name: php-gallery-manager
    # --- ADD THIS LINE ---
    image: tawsiftorabi/gallery-app:latest 
    build: .
    ports:
      - "8080:80"
    volumes:
      - /mnt/satahdd1/disk1/php-gallery-manager:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - db-network
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 1g

  php-video-worker:
    container_name: php-video-worker
    # --- ADD THIS LINE ---
    image: tawsiftorabi/gallery-worker:latest
    build: .
    command: php /var/www/html/worker.php 
    volumes:
      - /mnt/satahdd1/disk1/php-gallery-manager:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - db-network
    restart: always
    cpus: 2.0
    mem_limit: 2g

networks:
  db-network:
    external: true